### ISSUE TITLE
App bị crash khi sử dụng Full flow ở bước xác thực khuôn mặt.

### ISSUE THREAD

**Issue by trinhhcse** [vnptekyc/ekyc-android-sdk-samples#4]
`Intent intent = new Intent(context.getCurrentActivity(), VnptIdentityActivity.class);
        intent.putExtra(ACCESS_TOKEN,this.accessToken);
        intent.putExtra(TOKEN_ID,this.tokenId);
        intent.putExtra(TOKEN_KEY,this.tokenKey);
        intent.putExtra(SELECT_DOCUMENT, false);
        intent.putExtra(ID_TYPE, SDKEnum.DocumentIdTypeEnum. IDENTITY_CARD.getValue());
        intent.putExtra(VERSION_SDK, SDKEnum.VersionSDKEnum.ADVANCED.getValue());
        intent.putExtra(SHOW_SWITCH, false);
        intent.putExtra(SHOW_DIALOG_SUPPORT, false);
        intent.putExtra(SHOW_RESULT, true);
        intent.putExtra(CAMERA_FOR_PORTRAIT, SDKEnum.CameraTypeEnum.FRONT.getValue());
        intent.putExtra(CHECK_MASKED_FACE, true);
        intent.putExtra(CHECK_LIVENESS_CARD, true);`

Log: E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mservice, PID: 13553
    java.lang.NoSuchMethodError: No virtual method a()V in class Lcom/airbnb/lottie/LottieAnimationView; or its super classes (declaration of 'com.airbnb.lottie.LottieAnimationView' appears in /data/app/com.****-wwZC5nKoQuW9GY-5LDivlA==/base.apk)
        at a.c.a.a.b.q.a(:1)
        at a.c.a.a.b.q$d.a(:2)
        at a.c.a.a.b.q$d.onPreExecute(Unknown Source:10)
        at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:708)
        at android.os.AsyncTask.execute(AsyncTask.java:655)
        at a.c.a.a.b.q$c.run(:5)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7403)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by ngocphung247** [comment]
Bạn có thể copy nội dung file build.gradle (app level) lên đây được không ?
